repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'
    hooks:
      - id: poetry-export
        name: 匯出安裝套件
        args: [
          "-f", "requirements.txt",
          "-o", "requirements.txt"
        ]

  - repo: https://github.com/pycqa/isort
    rev: '5.13.2'
    hooks:
      - id: isort
        name: 調整 import 順序

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.5.2'
    hooks:
    -   id: ruff
        name: 自動格式化
        alias: autoformat
        args: [--fix]
